# Use root/example as user/password credentials

# docker run --name my-mariadb \
# -v /my/own/datadir:/var/lib/mysql
#-e MYSQL_ROOT_PASSWORD=root \
# -e MYSQL_DATABASE=dbtest \
# -e MYSQL_USER=komo \
# -e MYSQL_PASSWORD=komo \
# mariadb

#docker exec -it my-mariadb mysql -ukomo -pkomo

#/!\ Configurer les volumes

version: '3'

services:

  db:
    image: komo/srvmysql
    container_name: srvmysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "Bd_rpi"
      MYSQL_USER: "myRpi"
      MYSQL_PASSWORD: "rpi"
    volumes:
      - ./db-data:/var/lib/mysql


  web:
    build:
            context: ./mesDockerfile
            dockerfile: Dockerfile-lamp
    image: my-apache
    container_name: lamp
    depends_on:
      - db
    restart: always
    volumes:
      - ./public-html:/var/www/html
    ports:
      - 8080:80
    links:
      - "db:srvmysql"

        #  volumes:
        #db-data:
        #public-html:
        
