FROM debian:stable
RUN apt-get update && apt-get install -y apache2 php7.3 php7.3-cli php7.3-mysql
RUN echo "ServerName $(hostname)" >> /etc/apache2/apache2.conf
EXPOSE 80 443
#VOLUME ["/var/www", "/var/log/apache2", "/etc/apache2"]
ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
